<div class="social-media-links">
    <a href="<?=$aa['instance']['fb_page_url'];?>" target="_blank">
        <img src="img/icons/facebook-variation.png" alt="Facebook" class="grayscale" />
    </a>
    <?php if ( $aa['config']['header_sm_twitter']['value'] != "" ) { ?>
    <a href="<?=$aa['config']['header_sm_twitter']['value'];?>" target="_blank">
        <img src="img/icons/twitter-variation.png" alt="Twitter" class="grayscale" />
    </a>
    <?php }  ?>
    <?php if ( $aa['config']['header_sm_youtube']['value'] != "" ) { ?>
    <a href="<?=$aa['config']['header_sm_youtube']['value'];?>" target="_blank">
        <img src="img/icons/youtube-variation.png" alt="Youtube" class="grayscale" />
    </a>
    <?php }  ?>
    <?php if ( $aa['config']['header_sm_xing']['value'] != "" ) { ?>
    <a href="<?=$aa['config']['header_sm_xing']['value'];?>" target="_blank">
        <img src="img/icons/xing-variation.png" alt="Xing" class="grayscale" />
    </a>
    <?php }  ?>
    <?php if ( $aa['config']['header_sm_pinterest']['value'] != "" ) { ?>
        <a href="<?=$aa['config']['header_sm_pinterest']['value'];?>" target="_blank">
            <img src="img/icons/pinterest.png" alt="Pinterest" class="grayscale" />
        </a>
    <?php }  ?>
    <?php if ( $aa['config']['header_sm_tumblr']['value'] != "" ) { ?>
        <a href="<?=$aa['config']['header_sm_tumblr']['value'];?>" target="_blank">
            <img src="img/icons/tumblr-variation.png" alt="Tumblr" class="grayscale" />
        </a>
    <?php }  ?>
    <?php if ( $aa['config']['header_sm_instagram']['value'] != "" ) { ?>
        <a href="<?=$aa['config']['header_sm_instagram']['value'];?>" target="_blank">
            <img src="img/icons/instagram-variation.png" alt="Instagram" class="grayscale" />
        </a>
    <?php }  ?>
    <?php if ( $aa['config']['header_sm_blog']['value'] != "" ) { ?>
        <a href="<?=$aa['config']['header_sm_blog']['value'];?>" target="_blank">
            <img src="img/icons/blogger-variation.png" alt="Blog" class="grayscale" />
        </a>
    <?php }  ?>
</div>