<?php
$menu = explode(",", $aa['config']['menu_order']['value']);
var_dump($menu);
?>

<div class="left-nav">
    <ul class="nav nav-tabs nav-stacked">
        <?php
        // Generate menu
        foreach ( $menu as $item ) {
            if ( $item = "1" ) {
                $template = "index.phtml";
                $showItem = true;
            } else {
                $template = "page" . $item . ".phtml";
                if ( $aa['config']['page' . $item . '_activated']['value'] ) {
                    $showItem = true;
                } else {
                    $showItem = false;
                }
            }
            if ( $showItem ) { ?>
                <li>
                    <a onclick="aa_tmpl_load('<?=$template;?>', {target:'#main',effect:'fade'});">
                        <?=$aa['config']['page' . $item . '_caption']['value']?> <?php var_dump($item); ?>
                    </a>
                </li>
        <?php }
        } ?>
    </ul>
</div>