<?php
include_once ( '../init.php' );
require_once('../libs/Zend/Feed/Rss.php');
require_once('../libs/Zend/Feed/Atom.php');
require_once('../libs/Zend/Feed/');
require_once('../libs/Zend/Feed/Reader.php');
try {
    $links = Zend_Feed_Reader::findFeedLinks( $aa['config']['rss_feed1_url']['value'] );

    foreach ($links as $link) {
        $feed = Zend_Feed_Reader::import( $link['uri'] );
    }

}
catch (Exception $e){
    var_dump($e);
}

?>
<!-- Social News Page -->
<div class="page2">
    <div class="row">
        <div class="span2">
            <div class="logo">
                <?=$aa['config']['header_logo']['value'];?>
            </div>

            <?php if ( $aa['config']['header_sm_activated']['value'] ) {
            include_once("menu_social_media.phtml");
        }  ?>

            <?php include_once("menu_left.phtml"); ?>
        </div>

        <!-- RSS Feed Items -->
        <div class="span8">
            <h3><?=$feed->getTitle();?></h3>
            <h4>Anzahl Elemente: <?=$feed->count();?></h4>
            <?php
            foreach ( $feed as $item ) { ?>
                <div class="item">
                    <div class="thumbnail pull-left">
                        <?php
                        echo $item->getTitle() . "<br>";
                        echo $item->getLink() . "<br>";
                        echo $item->getDescription() . "<br>";
                        echo $item->getAuthor() . "<br>";
                        echo $item->getCategory() . "<br>";
                        echo $item->getComments() . "<br>";
                        echo $item->getPubDate() . "<br>";
                        ?>
                    </div>
                </div>
            <?php } ?>



        </div>

    </div>
</div> <!-- End welcome div live -->