<?php
include_once ( '../init.php' );
require_once('../libs/Zend/Feed/Rss.php');
require_once('../libs/Zend/Feed/Reader.php');
try {
    $channel = new Zend_Feed_Rss( $aa['config']['rss_feed1_url']['value'] );
    $feedArray = Zend_Feed::findFeeds('http://www.iconsultants.eu/blog/');

    $links = Zend_Feed_Reader::findFeedLinks('http://www.iconsultants.eu/blog/');

    if(isset($links->rdf)) {
        echo $links->rdf, "\n"; // http://www.planet-php.org/rdf/
    }
    if(isset($links->rss)) {
        echo $links->rss, "\n"; // http://www.planet-php.org/rss/
    }
    if(isset($links->atom)) {
        echo $links->atom, "\n"; // http://www.planet-php.org/atom/
    }

}
catch (Exception $e){
    var_dump($e);
}

?>
<!-- Social News Page -->
<div class="page2">
    <div class="row">
        <div class="span2">
            <div class="logo">
                <?=$aa['config']['header_logo']['value'];?>
            </div>

            <?php if ( $aa['config']['header_sm_activated']['value'] ) {
            include_once("menu_social_media.phtml");
        }  ?>

            <?php include_once("menu_left.phtml"); ?>
        </div>

        <!-- RSS Feed Items -->
        <div class="span8">
            <h3><?=$channel->title();?></h3>
            <p>
                Feeds:
                <?php var_dump($feedArray); ?>
            </p>
            <?php
            foreach ( $channel as $item ) { ?>
                <div class="item">
                    <div class="thumbnail pull-left">
                        <?php
                        echo $item->getTitle() . "<br>";
                        echo $item->getLink() . "<br>";
                        echo $item->getDescription() . "<br>";
                        echo $item->getAuthor() . "<br>";
                        echo $item->getCategory() . "<br>";
                        echo $item->getComments() . "<br>";
                        echo $item->getPubDate() . "<br>";
                        ?>
                    </div>
                </div>
            <?php } ?>



        </div>

    </div>
</div> <!-- End welcome div live -->