<?php
include_once ( '../init.php' );

// Contact form tab

$pages = explode( ",", $aa['config']['slider_pages']['value'] );
if ( in_array("6",$pages ) ){
    include_once('slider.phtml');
}
?>
<script>
    $('.nav-item').removeClass('active');
    $('.nav-item-6').addClass('active');
</script>

<div class="content">
    <?=$aa['config']['page6_content']['value'];?>
</div>

<div class="contact-form">
    <form class="form-horizontal" action="void();" id="form-modal">
        <div class="row">
            <div class="control-group span2">
                <label><?php __p('gender'); ?></label>
                <select class="span2">
                    <option><?php __p('male'); ?></option>
                    <option><?php __p('female'); ?></option>
                </select>
            </div>
            <div class="control-group span3">
                <label><?php __p('firstname'); ?></label>
                <input type="text" id="firstname" placeholder="<?php __p('firstname'); ?>" class="required span3">
            </div>
            <div class="control-group span3">
                <label><?php __p('lastname'); ?></label>
                <input type="text" id="lastname" placeholder="<?php __p('lastname'); ?>" class="required span3">
            </div>
        </div>
        <div class="row">
            <div class="control-group span4">
                <label><?php __p('email'); ?></label>
                <div class="input-prepend">
                    <input class="span4 required email" placeholder="<?php __p('email'); ?>" id="email" type="text">
                </div>
            </div>
            <div class="control-group span4">
                <label class="checkbox">
                    <input type="checkbox" id="newsletter_registration" value="1">
                    <?php __p('newsletter_registration'); ?>
                </label>
            </div>
        </div>

    </form>
</div>
