<?php
include_once ( '../init.php' );
?>
<!-- Team Page -->
<div class="page2">
    <div class="row">
        <div class="span2">
            <div class="logo">
                <?=$aa['config']['header_logo']['value'];?>
            </div>

            <?php if ( $aa['config']['header_sm_activated']['value'] ) { ?>
            <div class="social-media-links">
                <a href="<?=$aa['instance']['fb_page_url'];?>">
                    <img src="img/icons/facebook-variation.png" alt="Facebook" />
                </a>
                <?php if ( $aa['config']['header_sm_twitter']['value'] != "" ) { ?>
                <a href="<?=$aa['config']['header_sm_twitter']['value'];?>">
                    <img src="img/icons/twitter-variation.png" alt="Twitter" />
                </a>
                <?php }  ?>
                <?php if ( $aa['config']['header_sm_youtube']['value'] != "" ) { ?>
                <a href="<?=$aa['config']['header_sm_youtube']['value'];?>">
                    <img src="img/icons/youtube-variation.png" alt="Youtube" />
                </a>
                <?php }  ?>
                <?php if ( $aa['config']['header_sm_xing']['value'] != "" ) { ?>
                <a href="<?=$aa['config']['header_sm_xing']['value'];?>">
                    <img src="img/icons/xing-variation.png" alt="Youtube" />
                </a>
                <?php }  ?>
            </div>
            <?php }  ?>

            <?php include_once("menu_left.phtml"); ?>
        </div>
        <div class="span8">
            <div class="content">
                <?=$aa['config']['page2_content']['value'];?>
            </div>

            <div class="row member">
                <div class="span3 picture">
                    <img src="<?=$aa['config']['team_member1']['value'];?>" >
                </div>
                <div class="span5 description">
                    <?=$aa['config']['team_member1_desc']['value'];?>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End welcome div live -->