<?php
include_once ( '../init.php' );
?>
<div class="page2">
    <div class="row">
        <div class="span1">
            <div class="logo"></div>
            <?php include_once("templates/menu_left.phtml"); ?>
        </div>
        <div class="span9">
            <div class="content">
                <?=$aa['config']['page2_content']['value'];?>
            </div>
        </div>
    </div>
</div> <!-- End welcome div live -->